#!/usr/bin/env python3
"""Joins src/*.js, in name order, into index.js.

KMG runs a plugin as one index.js (app/src/plugin/loader.ts), so the sources
are plain script fragments sharing one scope. index.js is committed; the
kmg-package CI runs `build.py --check` to catch an index.js older than src/.
"""
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
HEADER = "// KMG Ink. Generated by build.py from src/: edit those files, then run build.py.\n"


def build() -> str:
    parts = [HEADER]
    for path in sorted((HERE / "src").glob("*.js")):
        parts.append(f"\n// ---- src/{path.name} ----\n\n")
        parts.append(path.read_text(encoding="utf-8").rstrip("\n") + "\n")
    return "".join(parts)


def main() -> int:
    target = HERE / "index.js"
    code = build()
    if sys.argv[1:] == ["--check"]:
        if target.read_text(encoding="utf-8") != code:
            print("kmg-ink: index.js is out of date; run kmg/plugins/kmg-ink/build.py", file=sys.stderr)
            return 1
        return 0
    target.write_text(code, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
